## YAML Template.
---
name: Tutorial
main: org.bukkit.awesomepants.tutorial.Tutorial
version: 0.2
website: http://bukkitfun.tumblr.com/
author: AwesomePants
description: Tutorial Stuff
commands:
  tutorial:
    description: Long command form.
    usage: |
           Usage -
           /<command> player - Player related commands.
           /<command> help - Displays help.
           /<command> help <subcommand> - Displays detailed help for the subcommand specified.
  tut:
    description: Short command form.
    usage: |
           Usage -
           /<command> player - Player related commands.
           /<command> help - Displays help.
           /<command> help <subcommand> - Displays detailed help for the subcommand specified.
