name: Tutorial
description: Tutorial Stuff
author: Kaletam
website: http://bukkitfun.tumblr.com/
main: org.bukkit.awesomepants.tutorial.Tutorial
version: 0.1
commands:
    tutorial:
        description: Long command form.
        usage: /<command>
    tut:
        description: Short command form.
        usage: /<command> [player]
